// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/poapogoogle258/myjob_interview/internel/handler"
	"github.com/poapogoogle258/myjob_interview/internel/repository"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func initializeServer(db *mongo.Database) *gin.Engine {
	jobRepository := repository.NewJobRepository(db)
	jobHandler := handler.NewJobHandler(jobRepository)
	engine := NewRouter(jobHandler)
	return engine
}
