// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/poapogoogle258/myjob_interview/internel/handler"
	"github.com/poapogoogle258/myjob_interview/internel/repository"
	"github.com/poapogoogle258/myjob_interview/internel/usecase"
	"github.com/poapogoogle258/myjob_interview/internel/utils/logger"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func initializeServer(db *mongo.Database) *App {
	jobRepository := repository.NewJobRepository(db)
	slogLogger := logger.NewLogger()
	scraperUsecase := usecase.NewScraperUsecase(jobRepository, slogLogger)
	jobHandler := handler.NewJobHandler(jobRepository, scraperUsecase)
	engine := NewRouter(jobHandler)
	app := &App{
		Router:  engine,
		Scraper: scraperUsecase,
	}
	return app
}

// wire.go:

type App struct {
	Router  *gin.Engine
	Scraper *usecase.ScraperUsecase
}
